### PR TITLE
Impwement uwu-mode :3

### PR DESCRIPTION
**Pull request by elkowar**
This PW impwements #9, adding two nyew options: uwu and UwU :3

### CODE REVIEW

**Review by exorcist365 — APPROVED** [review]
Seems legit

**Review by eepykate — APPROVED** [review]

**Review by buffet — APPROVED** [review]
Finally a good use case for Plover!

**Comment by exorcist365** [comment]
ikr

**Comment by psethwick** [comment]
Looks coo on my phone, will look properly later today!

Mind adding a line or two on the readme about the new modes @elkowar ?

**Comment by elkowar** [comment]
Added it to the weadme :3

**Review by psethwick — APPROVED** [review]

**Pull request merged**
