### PR TITLE
Add rudimentary morse mode

### PR DESCRIPTION
**Pull request by aerickt**
I wanted to add a mode to translate text into Morse code, but it doesn't work as well as I'd hoped. Currently I have the every letter mapped to its translation in Morse and also with a space after it. This is not really ideal, but I couldn't figure out a way to put a space in between every character. I also couldn't figure out if I can change the space character between words to a slash, so currently I'm just using `{:fancytext_set:morse}{MODE:SET_SPACE:/}`.

I'm not sure if this is something you want to improve, but I'm opening this PR just in case it is something you're interested in.

### CODE REVIEW

**Comment by aerickt** [comment]
Oh and also stroking `TK-LS` will reset the mode, bizarrely.
I might look into this later.

Space characters for multiword briefs also don't get translated into slashes.

**Comment by psethwick** [comment]
Siiick, love it!

I got some thoughts for tidy up on the spaces. Plan would be to extend the substitute class and return ' '.join(characters) there. I don't mind picking that up if you don't follow, let me know!

The TK-LS thing I've seen before, it's definitely unrelated to your changes. Probably belongs in a separate issue

**Comment by aerickt** [comment]
Nice! Everything I've done in this PR is all I really can do (not a programmer). You can absolutely pick up from where I left off. Thanks again for this awesome plugin!

**Comment by psethwick** [comment]
Not a problem at all! Thanks for the pr!

**Pull request merged**
