### PR TITLE
Add Small Caps

### PR DESCRIPTION
**Pull request by JorWat25**

### CODE REVIEW

**Comment by JorWat25** [comment]
Have probably done this wrong... Not familiar with GitHub.

Yep, managed to not actually update the relevant file. Will try again.

**Comment by JorWat25** [comment]
Right, hopefully this is right now.

**Comment by psethwick** [comment]
Yep, looks good to me!

Mind adding a bit to the readme?

**Comment by JorWat25** [comment]
That good?

**Comment by psethwick** [comment]
Excellent :-)

Thanks for the contribution!

**Pull request merged**
